### ISSUE TITLE
kan inte få path webdriver.Chrome(PATH) att fungera

### ISSUE THREAD

**Issue by EyedBread** [EyedBread/Kortletarna#3]
Får detta meddelande som error:

hello World!
hello World!
Traceback (most recent call last):
  File "/home/karlo/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './chromedriver.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/karlo/pro-kortletarna/Kortletarna/webCheckers/single-Webhallen.py", line 6, in <module>
    driver = webdriver.Chrome(executable_path = r'./chromedriver.exe')
  File "/home/karlo/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/home/karlo/.local/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable may have wrong permissions. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by EyedBread** [comment]
Tror jag har hittat en temporär lösning, om man från sin git bash terminal kör exempelvis "start single-Webhallen.py" så funkar programmet som den ska men om jag av någon anledning kör pythonkoden i vs-code och kör den där så uppstår detta fel
